// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: TrainTicket.proto

package TrainTicket

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JourneyDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From string `protobuf:"bytes,1,opt,name=From,proto3" json:"From,omitempty"`
	To   string `protobuf:"bytes,2,opt,name=To,proto3" json:"To,omitempty"`
}

func (x *JourneyDetails) Reset() {
	*x = JourneyDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TrainTicket_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JourneyDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JourneyDetails) ProtoMessage() {}

func (x *JourneyDetails) ProtoReflect() protoreflect.Message {
	mi := &file_TrainTicket_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JourneyDetails.ProtoReflect.Descriptor instead.
func (*JourneyDetails) Descriptor() ([]byte, []int) {
	return file_TrainTicket_proto_rawDescGZIP(), []int{0}
}

func (x *JourneyDetails) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *JourneyDetails) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type BookingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JourneyDetails *JourneyDetails `protobuf:"bytes,1,opt,name=journeyDetails,proto3" json:"journeyDetails,omitempty"`
	FirstName      string          `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName       string          `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email          string          `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *BookingRequest) Reset() {
	*x = BookingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TrainTicket_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingRequest) ProtoMessage() {}

func (x *BookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_TrainTicket_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingRequest.ProtoReflect.Descriptor instead.
func (*BookingRequest) Descriptor() ([]byte, []int) {
	return file_TrainTicket_proto_rawDescGZIP(), []int{1}
}

func (x *BookingRequest) GetJourneyDetails() *JourneyDetails {
	if x != nil {
		return x.JourneyDetails
	}
	return nil
}

func (x *BookingRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *BookingRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *BookingRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type BookingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JourneyDetails *JourneyDetails `protobuf:"bytes,1,opt,name=journeyDetails,proto3" json:"journeyDetails,omitempty"`
	User           string          `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	PricePaid      string          `protobuf:"bytes,3,opt,name=pricePaid,proto3" json:"pricePaid,omitempty"`
	TicketID       string          `protobuf:"bytes,4,opt,name=ticketID,proto3" json:"ticketID,omitempty"`
	SeatNo         string          `protobuf:"bytes,5,opt,name=seatNo,proto3" json:"seatNo,omitempty"`
}

func (x *BookingResponse) Reset() {
	*x = BookingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TrainTicket_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingResponse) ProtoMessage() {}

func (x *BookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_TrainTicket_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingResponse.ProtoReflect.Descriptor instead.
func (*BookingResponse) Descriptor() ([]byte, []int) {
	return file_TrainTicket_proto_rawDescGZIP(), []int{2}
}

func (x *BookingResponse) GetJourneyDetails() *JourneyDetails {
	if x != nil {
		return x.JourneyDetails
	}
	return nil
}

func (x *BookingResponse) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *BookingResponse) GetPricePaid() string {
	if x != nil {
		return x.PricePaid
	}
	return ""
}

func (x *BookingResponse) GetTicketID() string {
	if x != nil {
		return x.TicketID
	}
	return ""
}

func (x *BookingResponse) GetSeatNo() string {
	if x != nil {
		return x.SeatNo
	}
	return ""
}

type TicketDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TicketID string `protobuf:"bytes,1,opt,name=ticketID,proto3" json:"ticketID,omitempty"`
}

func (x *TicketDetails) Reset() {
	*x = TicketDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TrainTicket_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketDetails) ProtoMessage() {}

func (x *TicketDetails) ProtoReflect() protoreflect.Message {
	mi := &file_TrainTicket_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketDetails.ProtoReflect.Descriptor instead.
func (*TicketDetails) Descriptor() ([]byte, []int) {
	return file_TrainTicket_proto_rawDescGZIP(), []int{3}
}

func (x *TicketDetails) GetTicketID() string {
	if x != nil {
		return x.TicketID
	}
	return ""
}

type SectionDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SectionID string `protobuf:"bytes,1,opt,name=sectionID,proto3" json:"sectionID,omitempty"`
}

func (x *SectionDetails) Reset() {
	*x = SectionDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TrainTicket_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SectionDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SectionDetails) ProtoMessage() {}

func (x *SectionDetails) ProtoReflect() protoreflect.Message {
	mi := &file_TrainTicket_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SectionDetails.ProtoReflect.Descriptor instead.
func (*SectionDetails) Descriptor() ([]byte, []int) {
	return file_TrainTicket_proto_rawDescGZIP(), []int{4}
}

func (x *SectionDetails) GetSectionID() string {
	if x != nil {
		return x.SectionID
	}
	return ""
}

type CancellationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CancellationResult string `protobuf:"bytes,1,opt,name=cancellationResult,proto3" json:"cancellationResult,omitempty"`
}

func (x *CancellationResponse) Reset() {
	*x = CancellationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TrainTicket_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancellationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancellationResponse) ProtoMessage() {}

func (x *CancellationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_TrainTicket_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancellationResponse.ProtoReflect.Descriptor instead.
func (*CancellationResponse) Descriptor() ([]byte, []int) {
	return file_TrainTicket_proto_rawDescGZIP(), []int{5}
}

func (x *CancellationResponse) GetCancellationResult() string {
	if x != nil {
		return x.CancellationResult
	}
	return ""
}

type SeatAllotment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatAllotmentArray []*SeatAllotmentArray `protobuf:"bytes,1,rep,name=seatAllotmentArray,proto3" json:"seatAllotmentArray,omitempty"`
}

func (x *SeatAllotment) Reset() {
	*x = SeatAllotment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TrainTicket_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeatAllotment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatAllotment) ProtoMessage() {}

func (x *SeatAllotment) ProtoReflect() protoreflect.Message {
	mi := &file_TrainTicket_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatAllotment.ProtoReflect.Descriptor instead.
func (*SeatAllotment) Descriptor() ([]byte, []int) {
	return file_TrainTicket_proto_rawDescGZIP(), []int{6}
}

func (x *SeatAllotment) GetSeatAllotmentArray() []*SeatAllotmentArray {
	if x != nil {
		return x.SeatAllotmentArray
	}
	return nil
}

type SeatAllotmentArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatNo string `protobuf:"bytes,1,opt,name=seatNo,proto3" json:"seatNo,omitempty"`
	User   string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *SeatAllotmentArray) Reset() {
	*x = SeatAllotmentArray{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TrainTicket_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeatAllotmentArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatAllotmentArray) ProtoMessage() {}

func (x *SeatAllotmentArray) ProtoReflect() protoreflect.Message {
	mi := &file_TrainTicket_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatAllotmentArray.ProtoReflect.Descriptor instead.
func (*SeatAllotmentArray) Descriptor() ([]byte, []int) {
	return file_TrainTicket_proto_rawDescGZIP(), []int{7}
}

func (x *SeatAllotmentArray) GetSeatNo() string {
	if x != nil {
		return x.SeatNo
	}
	return ""
}

func (x *SeatAllotmentArray) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type NoParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NoParam) Reset() {
	*x = NoParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TrainTicket_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoParam) ProtoMessage() {}

func (x *NoParam) ProtoReflect() protoreflect.Message {
	mi := &file_TrainTicket_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoParam.ProtoReflect.Descriptor instead.
func (*NoParam) Descriptor() ([]byte, []int) {
	return file_TrainTicket_proto_rawDescGZIP(), []int{8}
}

type AllBookings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookingResponse []*BookingResponse `protobuf:"bytes,1,rep,name=bookingResponse,proto3" json:"bookingResponse,omitempty"`
}

func (x *AllBookings) Reset() {
	*x = AllBookings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TrainTicket_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllBookings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllBookings) ProtoMessage() {}

func (x *AllBookings) ProtoReflect() protoreflect.Message {
	mi := &file_TrainTicket_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllBookings.ProtoReflect.Descriptor instead.
func (*AllBookings) Descriptor() ([]byte, []int) {
	return file_TrainTicket_proto_rawDescGZIP(), []int{9}
}

func (x *AllBookings) GetBookingResponse() []*BookingResponse {
	if x != nil {
		return x.BookingResponse
	}
	return nil
}

var File_TrainTicket_proto protoreflect.FileDescriptor

var file_TrainTicket_proto_rawDesc = []byte{
	0x0a, 0x11, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x34, 0x0a, 0x0e, 0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x65, 0x79, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x54, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x54, 0x6f, 0x22, 0x99, 0x01, 0x0a, 0x0e, 0x42, 0x6f,
	0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x0e,
	0x6a, 0x6f, 0x75, 0x72, 0x6e, 0x65, 0x79, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x65, 0x79, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x0e, 0x6a, 0x6f, 0x75, 0x72, 0x6e, 0x65, 0x79, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0xb0, 0x01, 0x0a, 0x0f, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0e, 0x6a, 0x6f, 0x75,
	0x72, 0x6e, 0x65, 0x79, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x65, 0x79, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x52, 0x0e, 0x6a, 0x6f, 0x75, 0x72, 0x6e, 0x65, 0x79, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x69, 0x63, 0x65, 0x50,
	0x61, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x50, 0x61, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x44,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x44,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x74, 0x4e, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x65, 0x61, 0x74, 0x4e, 0x6f, 0x22, 0x2b, 0x0a, 0x0d, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x49, 0x44, 0x22, 0x2e, 0x0a, 0x0e, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x44, 0x22, 0x46, 0x0a, 0x14, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a,
	0x12, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x63, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x54, 0x0a,
	0x0d, 0x53, 0x65, 0x61, 0x74, 0x41, 0x6c, 0x6c, 0x6f, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x43,
	0x0a, 0x12, 0x73, 0x65, 0x61, 0x74, 0x41, 0x6c, 0x6c, 0x6f, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x41,
	0x72, 0x72, 0x61, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x53, 0x65, 0x61,
	0x74, 0x41, 0x6c, 0x6c, 0x6f, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x52,
	0x12, 0x73, 0x65, 0x61, 0x74, 0x41, 0x6c, 0x6c, 0x6f, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x72,
	0x72, 0x61, 0x79, 0x22, 0x40, 0x0a, 0x12, 0x53, 0x65, 0x61, 0x74, 0x41, 0x6c, 0x6c, 0x6f, 0x74,
	0x6d, 0x65, 0x6e, 0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x61,
	0x74, 0x4e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x61, 0x74, 0x4e,
	0x6f, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x09, 0x0a, 0x07, 0x4e, 0x6f, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x22, 0x49, 0x0a, 0x0b, 0x41, 0x6c, 0x6c, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x73, 0x12,
	0x3a, 0x0a, 0x0f, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0f, 0x62, 0x6f, 0x6f, 0x6b,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xc5, 0x02, 0x0a, 0x0b,
	0x54, 0x72, 0x61, 0x69, 0x6e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x2f, 0x0a, 0x0a, 0x42,
	0x6f, 0x6f, 0x6b, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x0f, 0x2e, 0x42, 0x6f, 0x6f, 0x6b,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x42, 0x6f, 0x6f,
	0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0c,
	0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x0e, 0x2e, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x1a, 0x15, 0x2e, 0x43,
	0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x12, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x12, 0x0e, 0x2e, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x1a, 0x10, 0x2e, 0x42, 0x6f, 0x6f, 0x6b,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x14, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x6f, 0x74, 0x6d,
	0x65, 0x6e, 0x74, 0x12, 0x0f, 0x2e, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x1a, 0x0e, 0x2e, 0x53, 0x65, 0x61, 0x74, 0x41, 0x6c, 0x6c, 0x6f, 0x74,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x0a, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x53, 0x65,
	0x61, 0x74, 0x12, 0x0e, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x1a, 0x10, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x54, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x08, 0x2e, 0x4e, 0x6f,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x1a, 0x0c, 0x2e, 0x41, 0x6c, 0x6c, 0x42, 0x6f, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x73, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x42, 0x6f, 0x6f,
	0x6b, 0x69, 0x6e, 0x67, 0x2f, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_TrainTicket_proto_rawDescOnce sync.Once
	file_TrainTicket_proto_rawDescData = file_TrainTicket_proto_rawDesc
)

func file_TrainTicket_proto_rawDescGZIP() []byte {
	file_TrainTicket_proto_rawDescOnce.Do(func() {
		file_TrainTicket_proto_rawDescData = protoimpl.X.CompressGZIP(file_TrainTicket_proto_rawDescData)
	})
	return file_TrainTicket_proto_rawDescData
}

var file_TrainTicket_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_TrainTicket_proto_goTypes = []interface{}{
	(*JourneyDetails)(nil),       // 0: JourneyDetails
	(*BookingRequest)(nil),       // 1: BookingRequest
	(*BookingResponse)(nil),      // 2: BookingResponse
	(*TicketDetails)(nil),        // 3: TicketDetails
	(*SectionDetails)(nil),       // 4: SectionDetails
	(*CancellationResponse)(nil), // 5: CancellationResponse
	(*SeatAllotment)(nil),        // 6: SeatAllotment
	(*SeatAllotmentArray)(nil),   // 7: SeatAllotmentArray
	(*NoParam)(nil),              // 8: NoParam
	(*AllBookings)(nil),          // 9: AllBookings
}
var file_TrainTicket_proto_depIdxs = []int32{
	0,  // 0: BookingRequest.journeyDetails:type_name -> JourneyDetails
	0,  // 1: BookingResponse.journeyDetails:type_name -> JourneyDetails
	7,  // 2: SeatAllotment.seatAllotmentArray:type_name -> SeatAllotmentArray
	2,  // 3: AllBookings.bookingResponse:type_name -> BookingResponse
	1,  // 4: TrainTicket.BookTicket:input_type -> BookingRequest
	3,  // 5: TrainTicket.CancelTicket:input_type -> TicketDetails
	3,  // 6: TrainTicket.CheckTicketReceipt:input_type -> TicketDetails
	4,  // 7: TrainTicket.CheckTicketAllotment:input_type -> SectionDetails
	3,  // 8: TrainTicket.ModifySeat:input_type -> TicketDetails
	8,  // 9: TrainTicket.GetAllTicketDetails:input_type -> NoParam
	2,  // 10: TrainTicket.BookTicket:output_type -> BookingResponse
	5,  // 11: TrainTicket.CancelTicket:output_type -> CancellationResponse
	2,  // 12: TrainTicket.CheckTicketReceipt:output_type -> BookingResponse
	6,  // 13: TrainTicket.CheckTicketAllotment:output_type -> SeatAllotment
	2,  // 14: TrainTicket.ModifySeat:output_type -> BookingResponse
	9,  // 15: TrainTicket.GetAllTicketDetails:output_type -> AllBookings
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_TrainTicket_proto_init() }
func file_TrainTicket_proto_init() {
	if File_TrainTicket_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_TrainTicket_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JourneyDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TrainTicket_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TrainTicket_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TrainTicket_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TicketDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TrainTicket_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SectionDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TrainTicket_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancellationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TrainTicket_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeatAllotment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TrainTicket_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeatAllotmentArray); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TrainTicket_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TrainTicket_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllBookings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_TrainTicket_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_TrainTicket_proto_goTypes,
		DependencyIndexes: file_TrainTicket_proto_depIdxs,
		MessageInfos:      file_TrainTicket_proto_msgTypes,
	}.Build()
	File_TrainTicket_proto = out.File
	file_TrainTicket_proto_rawDesc = nil
	file_TrainTicket_proto_goTypes = nil
	file_TrainTicket_proto_depIdxs = nil
}
