// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: TrainTicket.proto

package TrainTicket

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TrainTicketClient is the client API for TrainTicket service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrainTicketClient interface {
	BookTicket(ctx context.Context, in *BookingRequest, opts ...grpc.CallOption) (*BookingResponse, error)
	CancelTicket(ctx context.Context, in *TicketDetails, opts ...grpc.CallOption) (*CancellationResponse, error)
	CheckTicketReceipt(ctx context.Context, in *TicketDetails, opts ...grpc.CallOption) (*BookingResponse, error)
	CheckTicketAllotment(ctx context.Context, in *SectionDetails, opts ...grpc.CallOption) (*SeatAllotment, error)
	ModifySeat(ctx context.Context, in *TicketDetails, opts ...grpc.CallOption) (*BookingResponse, error)
	GetAllTicketDetails(ctx context.Context, in *NoParam, opts ...grpc.CallOption) (*AllBookings, error)
}

type trainTicketClient struct {
	cc grpc.ClientConnInterface
}

func NewTrainTicketClient(cc grpc.ClientConnInterface) TrainTicketClient {
	return &trainTicketClient{cc}
}

func (c *trainTicketClient) BookTicket(ctx context.Context, in *BookingRequest, opts ...grpc.CallOption) (*BookingResponse, error) {
	out := new(BookingResponse)
	err := c.cc.Invoke(ctx, "/TrainTicket/BookTicket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainTicketClient) CancelTicket(ctx context.Context, in *TicketDetails, opts ...grpc.CallOption) (*CancellationResponse, error) {
	out := new(CancellationResponse)
	err := c.cc.Invoke(ctx, "/TrainTicket/CancelTicket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainTicketClient) CheckTicketReceipt(ctx context.Context, in *TicketDetails, opts ...grpc.CallOption) (*BookingResponse, error) {
	out := new(BookingResponse)
	err := c.cc.Invoke(ctx, "/TrainTicket/CheckTicketReceipt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainTicketClient) CheckTicketAllotment(ctx context.Context, in *SectionDetails, opts ...grpc.CallOption) (*SeatAllotment, error) {
	out := new(SeatAllotment)
	err := c.cc.Invoke(ctx, "/TrainTicket/CheckTicketAllotment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainTicketClient) ModifySeat(ctx context.Context, in *TicketDetails, opts ...grpc.CallOption) (*BookingResponse, error) {
	out := new(BookingResponse)
	err := c.cc.Invoke(ctx, "/TrainTicket/ModifySeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainTicketClient) GetAllTicketDetails(ctx context.Context, in *NoParam, opts ...grpc.CallOption) (*AllBookings, error) {
	out := new(AllBookings)
	err := c.cc.Invoke(ctx, "/TrainTicket/GetAllTicketDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrainTicketServer is the server API for TrainTicket service.
// All implementations must embed UnimplementedTrainTicketServer
// for forward compatibility
type TrainTicketServer interface {
	BookTicket(context.Context, *BookingRequest) (*BookingResponse, error)
	CancelTicket(context.Context, *TicketDetails) (*CancellationResponse, error)
	CheckTicketReceipt(context.Context, *TicketDetails) (*BookingResponse, error)
	CheckTicketAllotment(context.Context, *SectionDetails) (*SeatAllotment, error)
	ModifySeat(context.Context, *TicketDetails) (*BookingResponse, error)
	GetAllTicketDetails(context.Context, *NoParam) (*AllBookings, error)
	mustEmbedUnimplementedTrainTicketServer()
}

// UnimplementedTrainTicketServer must be embedded to have forward compatible implementations.
type UnimplementedTrainTicketServer struct {
}

func (UnimplementedTrainTicketServer) BookTicket(context.Context, *BookingRequest) (*BookingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BookTicket not implemented")
}
func (UnimplementedTrainTicketServer) CancelTicket(context.Context, *TicketDetails) (*CancellationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelTicket not implemented")
}
func (UnimplementedTrainTicketServer) CheckTicketReceipt(context.Context, *TicketDetails) (*BookingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckTicketReceipt not implemented")
}
func (UnimplementedTrainTicketServer) CheckTicketAllotment(context.Context, *SectionDetails) (*SeatAllotment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckTicketAllotment not implemented")
}
func (UnimplementedTrainTicketServer) ModifySeat(context.Context, *TicketDetails) (*BookingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifySeat not implemented")
}
func (UnimplementedTrainTicketServer) GetAllTicketDetails(context.Context, *NoParam) (*AllBookings, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTicketDetails not implemented")
}
func (UnimplementedTrainTicketServer) mustEmbedUnimplementedTrainTicketServer() {}

// UnsafeTrainTicketServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrainTicketServer will
// result in compilation errors.
type UnsafeTrainTicketServer interface {
	mustEmbedUnimplementedTrainTicketServer()
}

func RegisterTrainTicketServer(s grpc.ServiceRegistrar, srv TrainTicketServer) {
	s.RegisterService(&TrainTicket_ServiceDesc, srv)
}

func _TrainTicket_BookTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainTicketServer).BookTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TrainTicket/BookTicket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainTicketServer).BookTicket(ctx, req.(*BookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainTicket_CancelTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TicketDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainTicketServer).CancelTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TrainTicket/CancelTicket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainTicketServer).CancelTicket(ctx, req.(*TicketDetails))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainTicket_CheckTicketReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TicketDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainTicketServer).CheckTicketReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TrainTicket/CheckTicketReceipt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainTicketServer).CheckTicketReceipt(ctx, req.(*TicketDetails))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainTicket_CheckTicketAllotment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SectionDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainTicketServer).CheckTicketAllotment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TrainTicket/CheckTicketAllotment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainTicketServer).CheckTicketAllotment(ctx, req.(*SectionDetails))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainTicket_ModifySeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TicketDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainTicketServer).ModifySeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TrainTicket/ModifySeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainTicketServer).ModifySeat(ctx, req.(*TicketDetails))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainTicket_GetAllTicketDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainTicketServer).GetAllTicketDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TrainTicket/GetAllTicketDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainTicketServer).GetAllTicketDetails(ctx, req.(*NoParam))
	}
	return interceptor(ctx, in, info, handler)
}

// TrainTicket_ServiceDesc is the grpc.ServiceDesc for TrainTicket service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrainTicket_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TrainTicket",
	HandlerType: (*TrainTicketServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BookTicket",
			Handler:    _TrainTicket_BookTicket_Handler,
		},
		{
			MethodName: "CancelTicket",
			Handler:    _TrainTicket_CancelTicket_Handler,
		},
		{
			MethodName: "CheckTicketReceipt",
			Handler:    _TrainTicket_CheckTicketReceipt_Handler,
		},
		{
			MethodName: "CheckTicketAllotment",
			Handler:    _TrainTicket_CheckTicketAllotment_Handler,
		},
		{
			MethodName: "ModifySeat",
			Handler:    _TrainTicket_ModifySeat_Handler,
		},
		{
			MethodName: "GetAllTicketDetails",
			Handler:    _TrainTicket_GetAllTicketDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "TrainTicket.proto",
}
